### ISSUE TITLE
As a developer I want to test the Azure SQL database with docker

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#107]
### User Story:

As a developer, I want to be able to test the Azure SQL Database using Docker so that I can have a consistent and isolated environment for testing.

### Description:

Currently, testing Azure SQL Database integration can be challenging due to the need for a live Azure environment. This can be problematic for various reasons including security concerns, cost considerations, and network dependencies.

### Proposed Solution:

Implement a Dockerized version of Azure SQL Database or provide guidance and a sample Docker Compose configuration that allows developers to set up a local environment for testing Azure SQL Database integration.

### Acceptance Criteria:

- [ ] A Docker image for Azure SQL Database or a sample Docker Compose configuration should be provided.
- [ ] The Docker image or configuration should be well-documented with clear instructions on how to use it.
- [ ] The Dockerized environment should allow developers to perform basic CRUD operations on the database.

### Additional Information:

- Any additional information, context, or related issues that may be relevant to this request.

### Labels:

- enhancement
- docker
- testing

### Priority:

- [ ] Low
- [x] Medium
- [ ] High

### Estimated Time:

- [ ] S - (small: a few hours or less)
- [x] M - (medium: a day or two)
- [ ] L - (large: several days to a week)

### Dependencies:

- List any related issues or tasks that this issue may depend on or be dependent on.

### Notes:

- Any additional notes or considerations that might be helpful for addressing this issue.

**Comment by hananinas** [comment]
Added docker and testing with GitHub actions is now working 
I have created a pull request #114 
Please take a look at it whenever you have time :)

**Comment by Josh0104** [comment]
I'll check it out at the end of this week. Nice work :D

**Comment by hananinas** [comment]
Nice I already merged the code but would still be nice if you could take a look at #114 thanks in advance🙂

**Comment by Josh0104** [comment]
I have reviewed it now as well as written a comment
