### ISSUE TITLE
As a developer I want to add UI tests using PlayWright to ensure that the required functionality of Chirp works

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#127]
- [x] Generate UI tests using PlayWright for testing functionality related to UI. At minimum, create test(s) for the scenario describe in the project work description for session 11. 

- [x] UI tests do not need to run as an integrated part of the GitHub Actions flow, but you should be able to execute them manually.

**Comment by hananinas** [comment]
Implemented
