### ISSUE TITLE
As a developer I want to test the program with and End-To-End test

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#137]
### Overview
We need to establish end-to-end tests for our application using the Playwright library. The tests will cover crucial user interactions related to authentication, cheep management, and social interactions.

#### User Login
- [x] Ensure that users can successfully log in using their email and password.
- [x] Validate the user's ability to log in and access the application.

#### Read Cheeps
- [x] Confirm that users can read cheeps after logging in.

#### Create Cheep
- [x] Verify the user's capability to create a new cheep.

#### Follow/Unfollow Users
- [x] Implement a test to check if a user can successfully follow another user.
- [x] Confirm the ability to unfollow a user.

#### React to Cheep
- [x] Create a test scenario where a user can react to a cheep.

### Additional Information
For implementation details and code samples, refer to the [Playwright documentation on authentication](https://playwright.dev/dotnet/docs/auth).

### Steps to Reproduce
1. Log in with a valid email and password.
2. Read existing cheeps.
3. Create a new cheep.
4. Follow another user.
5. Unfollow the followed user.
6. React to a cheep.

### Expected Result
All tests should pass, indicating that the application's core functionalities related to authentication, cheep management, and social interactions are working correctly.

### Notes
Provide any additional information or context that may be relevant to the implementation of these tests.

**Comment by hananinas** [comment]
This has been implemented
