### ISSUE TITLE
As a User I want to send cheeps again without getting an error

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#145]
### User Story
As a user, I want to be able to send cheeps without encountering errors.

### Description
Currently, there seems to be an issue when users try to submit cheeps. The application throws an error, preventing users from successfully posting their cheeps. We need to investigate and address this issue to ensure a seamless cheep submission experience.

### Steps to Reproduce
1. Log in to the Chirp application.
2. Navigate to the cheep submission interface.
3. Attempt to submit a cheep.

### Expected Behavior
Users should be able to submit cheeps without encountering any errors. The application should handle cheep submissions gracefully and provide appropriate feedback to the user.

### Additional Information
- Check server logs for any relevant error messages.
- Review the cheep submission code to identify and resolve the issue.
- Ensure that error messages, if any, are user-friendly and informative.

**Comment by hananinas** [comment]
This was fixed in a pull request
