### ISSUE TITLE
As a developer I want to use Docker container for development instead of Azure Sql in developer mode

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#187]
When you run our program locally it will connect to a test database in Azure SQL server. This is not a good idea when other users want to run it locally and does not have access to our server, since the connection string is hidden in Key Vault managed by azure sql, so it checks the user is in the white list. 

So in order to solve this issue, we change the program when run locally to use a Docker container, that is the same method we use when we run our integration test. 

So now for order to run our program locally you need to run Docker in your machine

**Comment by hananinas** [comment]
The issue has been fixed
