### ISSUE TITLE
As a developer I want to refactor the UserInterface to ensure improved readability and reduce the code length

### ISSUE THREAD

**Issue by Josh0104** [ITU-BDSA23-GROUP17/Chirp#33]
The current UserInterface has a lot of lines of code that needs to be refactor so there is more readability. 
Example: 
`using HttpClient client = new HttpClient();
`
Is both used in 
Line 61: `async public static Task appendFile(object[] args)`
Line 17: ` async public static Task printCheeps(int? limit = null)`

**Comment by MidweekAmphibian** [comment]
Acceptance criteria: 

- UserInterface class deals only with functionality and methods related to displaying cheeps. Functionality unrelated to this goal has been moved to program.cs or elsewhere. 

- Instances, where HttpClient is used within appendFile and printCheeps, should be changed so each method does one thing. Separate functions have been identified and moved into separate functions which call each other as needed.

**Comment by Burak123T** [comment]
UserInterface has now been successfully refactored. UserInterface now only deals with functionality and methods related to displaying cheeps. Note that UnixTimeParser is also deleted, and thus the Unit Tests has been rewritten to avoid errors!
