### ISSUE TITLE
As a developer, I want to add End-to-End Tests to Chirp! CLI App

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#41]
Acceptance criteria:   
- A test simulating running the program and entering “chirp read 10” in the terminal is created and verifies that the output matches the expected output. The test is able to pass without errors.  
- A test simulating entering ‘chirp cheep Hello!!!’ in the terminal is created and verifies that the respective values are stored in the database. The test is able to pass without errors.

**Comment by hananinas** [comment]
This has been done the test works on the computer but not on actions so the issue will be closed.
