### ISSUE TITLE
As a developer, I want to switch Database to File-based SQLite Database in order to expand and enhance the database functionality 

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#43]
Acceptance criteria: 

- Refactored code to retrieve Cheeps and authors from an SQLite database using the schema and the data dump.
- Database-related code (for establishing connections and access of data, etc) is encapsulated in its own "wrapper class" called DBFacade.cs
- Code in the method GetCheeps() in CheepService.cs has been modified so it executes an SQL query against the SQLite database. The signature of the method should remain the same.
- GetCheepsFromAuthor(string author) returns cheeps based on author.

**Comment by hananinas** [comment]
This issue has been addressed
