### ISSUE TITLE
As a developer, I want to move the existting CLI application code to another branch, in order to make space to dramatically change the code architecture and functionality 

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#47]
Acceptance criteria: 

- The existing code has been "retired" to a new branch, chirp_cli
- The branch is kept around to allow teachers and censors to assess the project at the end of the course. 
- The main branch contains the new Razor Page Chirp! application and associated test suites.

**Comment by hananinas** [comment]
This issue has been addressed the code is now in Chirp-cli branch.
