### ISSUE TITLE
As a developer, I want to add automatic deployment of the Razor Page App in order to continue automatically building and testing the application

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#48]
Acceptance criteria: 

- GitHub Actions workflow in the main branch has been refactored to build and test the new Razor Page Chirp! application. 
- the new Razor Page Chirp! application is deployed to Azure App Service when new versions are available in the main branch of the repository
- The Razor Page web application is reachable under the URL https://bdsagroup17chirprazor.azurewebsites.net/

**Comment by hananinas** [comment]
The issue has been addressed.
