### ISSUE TITLE
As a developer, I want to add unit tests which test functionality after refactored code/structure

### ISSUE THREAD

**Issue by MidweekAmphibian** [ITU-BDSA23-GROUP17/Chirp#70]
After restructuring the the code to make it Clean with Onion, and CQS we need to add/modify unit tests to correctly cover the modified/new components and functionality.
This includes testing the repository methods which create, read, update and delete data, data conversion and that the core functionality of the application remains intact.

Acceptance criteria: 

- [ ] All unit tests pass correctly

- [ ] Test coverage of critical repository methods and core application functionality

**Comment by Josh0104** [comment]
This issue has been resolve, but we forgot to close it
