### ISSUE TITLE
As a developer i want the userTimline to have the same cheeps 

### ISSUE THREAD

**Issue by hananinas** [ITU-BDSA23-GROUP17/Chirp#80]
I have noticed a discrepancy in the content displayed when accessing specific URLs with or without a page parameter.

1. Access the following URLs:
   - [URL without page parameter](https://bdsagroup17chirprazor.azurewebsites.net/Jacqualine%20Gilcoine)
   - [URL with page parameter](https://bdsagroup17chirprazor.azurewebsites.net/Jacqualine%20Gilcoine?page=1)

2. Describe the differences in the content you observe.

### Expected Behavior

The two pages should have equal amount of cheeps as they should be the same page.

### Actual Behavior

They are not the same page but page the page at / is 

https://bdsagroup17chirprazor.azurewebsites.net/Jacqualine%20Gilcoine?page=0

and at page=1 is 

https://bdsagroup17chirprazor.azurewebsites.net/Jacqualine%20Gilcoine?page=1

both should be 0 

### Additional Details

![Screenshot from 2023-10-24 12-36-54](https://github.com/ITU-BDSA23-GROUP17/Chirp/assets/24508160/e3143967-8c10-43ba-be38-818d227d9c0e)

![Screenshot from 2023-10-24 12-37-19](https://github.com/ITU-BDSA23-GROUP17/Chirp/assets/24508160/88cbde4b-c7b2-435f-8efd-a680aa78fd25)

![Screenshot from 2023-10-24 12-37-30](https://github.com/ITU-BDSA23-GROUP17/Chirp/assets/24508160/659bd7ec-259d-457e-a7ca-849a157297dd)

**Comment by Burak123T** [comment]
Its now fixed for both Public and User Timelines. When the user is at '?page=1' (or just empty query), then the 'back arrow' will disappear.

**Comment by hananinas** [comment]
Would be nice if you could implement a test to check of this specific issue using the newly created test branch
